version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server/data.json:/server/data.json